### ISSUE TITLE
Avatar doesn't apply after selecting it

### ISSUE THREAD

**Issue by Syping** [SyDevTeam/gta5view#13]
**The issue has being fixed, if there are problems again, please post here so i can reopen the issue if necessary.**

Some people report using the Game Overlay doesn't work... use the [Social Club website](https://socialclub.rockstargames.com/) instead.

> Many people reporting they can't set a new Avatar... it's a issue introduced from Rockstar Games in last Tuners DLC update. It affects non-gta5view users aswell.
>
> The reason is Rockstar Games moved their Snapmatic cloud server to a new location, and their new cloud server lacks the _small.jpg generation, which causes Rockstar Games backend to error when it tries to set a new Snapmatic Avatar.
>
> This GitHub issue will remain open so long it's known not being fixed. When it's fixed for you, please report it here.
>
> **Workaround (NOT WORKING ANYMORE)**
> > You can upload to the old cloud server with a downgraded GTA V installation, head to this [comment](#issuecomment-903236663) for more information.
> > This will allow you to set your new Snapmatic uploads as Avatar.
> [Game crash?](#issuecomment-903439990)

**Comment by clx127** [comment]
So Rockstar changed their cloud servers and any uploaded custom avatars will not work? Yesterday i uploaded my custom avatar but in settings/Snapmatic Mugshots my uploaded photos wont showed... But before few years ago all was ok

**Comment by stroop17wafflr** [comment]
> So cockstar changed their cloud servers and any uploaded custom avatars will not work? Yesterday i uploaded my custom avatar but in settings/Snapmatic Mugshots my uploaded photos wont showed... But before few years ago all was ok

Basically, yeah. Only thing we can do is wait for them to fix it, I suppose. I myself didn't have a custom avatar before they switched servers, so the "temporary fix" won't work for me.

God, can't R* go one update without messing something up?

**Comment by Syping** [comment]
They fixed some parts already, you can now select Avatar pictures again, applying a newer one fails still.

![halffix](https://user-images.githubusercontent.com/9694335/128099756-83748057-0760-4466-a4ac-b332bb34b25a.png)

**Comment by stroop17wafflr** [comment]
Well, at least they're getting somewhere with it, even if it's still broken.

**Comment by ahmedmadder1** [comment]
any updates ?

**Comment by stroop17wafflr** [comment]
Still wasn't fixed for me, so it probably doesn't work for anyone else still.

**Comment by Syping** [comment]
> any updates ?

Not yet, i hope they will fix the new backend soon, or at least adapt the Avatar system to the new backend, which not happend yet either.

**Comment by stroop17wafflr** [comment]
Still not working as of 15/8/2021.

**Comment by Syping** [comment]
**Update**: Downgrading GTA V to a previous version fixes the issue, it does upload to the old cloud server.
I will not count that as case closed still, i will keep the issue open until Rockstar fixes the new version uploads.

![Screenshot_20210822_104603](https://user-images.githubusercontent.com/9694335/130348792-1b50371f-0848-496c-9583-069857218522.png)

New Avatar uploaded from previous version.
![Screenshot_20210822_104604](https://user-images.githubusercontent.com/9694335/130348809-e55f28be-1cc9-4c4b-8c10-c017591d96e8.png)

**How to downgrade**
[Steam Version](https://www.youtube.com/watch?v=45ZE2tgsZe0)
[Rockstar Version](https://www.youtube.com/watch?v=wbmm6yOWf1Q)
[Epic Games Version](https://www.youtube.com/watch?v=ydUzcPzjW8s)
Please always check if the files are signed by Rockstar Games, you can do it by uploading the executables to [VirusTotal](https://www.virustotal.com/gui/home/upload).

**Comment by stroop17wafflr** [comment]
> **How to downgrade**
> [Steam Version](https://www.youtube.com/watch?v=45ZE2tgsZe0)

Using the linked method, **(Steam)** it seems to crash on loading, with nothing in the log pertaining to it, other than "Exit code 0x0 indicates a clean game shutdown". Because of this, I cannot access the gallery, in order to upload the Snapmatic. Maybe I'm doing something wrong? But I don't think so, since I followed it exactly, step-by-step, on a clean installation. This wouldn't be a problem, if this wasn't the only downgrade video, that isn't outdated.

I'll keep trying, and I'll update everyone if I can get it to work. If so, this comment will be edited. 

Edit: Eh, I give up for now. I've tried about everything I know when troubleshooting this kind of stuff, to no avail. I'll just hope for the best, and wait for them to roll out a patch.

**Comment by Syping** [comment]
> > **How to downgrade**
> > [Steam Version](https://www.youtube.com/watch?v=45ZE2tgsZe0)
> 
> Using the linked method, **(Steam)** it seems to crash on loading, with nothing in the log pertaining to it, other than "Exit code 0x0 indicates a clean game shutdown". Because of this, I cannot access the gallery, in order to upload the Snapmatic. Maybe I'm doing something wrong? But I don't think so, since I followed it exactly, step-by-step, on a clean installation. This wouldn't be a problem, if this wasn't the only downgrade video, that isn't outdated.
> 
> I'll keep trying, and I'll update everyone if I can get it to work. If so, this comment will be edited.
> 
> Edit: Eh, I give up for now. I've tried about everything I know when troubleshooting this kind of stuff, to no avail. I'll just hope for the best, and wait for them to roll out a patch.

You need to replace the update.rpf in the update folder aswell, i think that's your crash reason.
If you have put in the main folder, move it to the update folder instead.

The update folder where my mouse cursor is.
![Screenshot_20210823_065049](https://user-images.githubusercontent.com/9694335/130391679-14cb7abe-6519-4c71-900c-1267d28bc800.png)

Replace the update.rpf here.
![Screenshot_20210823_065133](https://user-images.githubusercontent.com/9694335/130391689-f1578d54-2f82-4862-bd7c-e13b7d04ff1a.png)

**Comment by stroop17wafflr** [comment]
Wow, don't I feel dumb... Thanks for pointing that out, or I probably would've never figured this out, especially with how unhelpful the logs were.

**Comment by stroop17wafflr** [comment]
Well, it's certainly working. Thanks for your help, @Syping.

**Comment by Syping** [comment]
> Well, it's certainly working. Thanks for your help, @Syping.

Great news, it would had being easier if the guy made the update folder inside the archive already. But it's cool he makes these because the depot downgrading method doesn't work anymore.

**Comment by stroop17wafflr** [comment]
> it would had being easier if the guy made the update folder inside the archive already.

Yeah, that kinda threw me off, since I thought it was just another case of dragging-and-dropping into the directory. Still my fault though, should've watched it to completion.

**Comment by Pronater** [comment]
I thank you for pointing out the error and for warning me of a possible temporary solution

**Comment by LONGACAT** [comment]
After downgrading the game, the upload fails with the following error: "Failed to save Snapmatic photo to Social Club. The Rockstar game services are unavaible right now. Please try again later". Is there any fix for this?

**Comment by Syping** [comment]
> After downgrading the game, the upload fails with the following error: "Failed to save Snapmatic photo to Social Club. The Rockstar game services are unavaible right now. Please try again later". Is there any fix for this?

Have no fix for that, i think Rockstar Games removed the workaround, as soon i do my testing again i will report back and edit the post what i got as result.
I really hope they fix the bug in Tuners DLC because i'm really not a big fan of the workaround.

**Comment by stroop17wafflr** [comment]
> After downgrading the game, the upload fails with the following error: "Failed to save Snapmatic photo to Social Club. The Rockstar game services are unavaible right now. Please try again later". Is there any fix for this?

Yep, also does it for me as well. Not sure how we're gonna get around this one.

**Comment by Syping** [comment]
> > After downgrading the game, the upload fails with the following error: "Failed to save Snapmatic photo to Social Club. The Rockstar game services are unavaible right now. Please try again later". Is there any fix for this?
> 
> Yep, also does it for me as well. Not sure how we're gonna get around this one.

Thanks for reporting, so i consider the workaround for broken now, i think they didn't liked Uploads pushed on their old Server by us lol.
**EDIT:** I have news.. it seems they moving old cloud server stuff to the new cloud server. The pictures which had being moved can't be selected anymore or be viewed on the Social Club website, still can get metadata etc. but not the .jpg file itself.

**Comment by stroop17wafflr** [comment]
> Thanks for reporting, so i consider the workaround for broken now, i think they didn't liked Uploads pushed on their old Server by us lol.
> **EDIT:** I have news.. it seems they moving old cloud server stuff to the new cloud server. The pictures which had being moved can't be selected anymore or be viewed on the Social Club website, still can get metadata etc. but not the .jpg file itself.

They're moving stuff, eh? Could they finally be adapting it, or something? Hopefully.

**Comment by MayoChiki** [comment]
> 
> 
> > After downgrading the game, the upload fails with the following error: "Failed to save Snapmatic photo to Social Club. The Rockstar game services are unavaible right now. Please try again later". Is there any fix for this?
> 
> Yep, also does it for me as well. Not sure how we're gonna get around this one.

I forgot to test but are selfies as custom avatars broken aswell? I'm guessing taking a selfie in-game and replacing it with the app doesn't work? Because if that's the case (avatars broken as a whole) then sadly there's no way to workaround for this since the feature doesn't work at all

**Comment by stroop17wafflr** [comment]
> I forgot to test but are selfies as custom avatars broken aswell? I'm guessing taking a selfie in-game and replacing it with the app doesn't work? Because if that's the case (avatars broken as a whole) then sadly there's no way to workaround for this since the feature doesn't work at all

Not sure. Guess I'll test it next time I get on.

Edit: Neither selfies, nor random snapmatics are popping up after I upload them. However, snapmatics I uploaded on the older version **(when it worked, at least)** are still popping up, and seem to be working fine. I don't know what this means, other than this probably isn't gonna work until R* fixes it themselves.

**Comment by Syping** [comment]
Yea, normal in-game selfies are broken, this is what gta5view uses to make them usable as Avatar. This why i can't fix anything in gta5view because there is nothing for me to fix for, i really hope R* will fix that as soon as possible, i can imagine normal Snapmatic users are annoyed aswell.

**Comment by SpiraIt** [comment]
dang its going to take weeks for the new servers like theirs millions of snapmatics

**Comment by Pronater** [comment]
they ruined my happiness to send personalized images, I'm going there to kill myself, then I'm back.

**Comment by igobythisname** [comment]
i don't use gta5view, but a few days ago i tried to upload a r* editor scene/snapshot as my avatar, that's when i learned only snapmatic selfies/mugshots are allowed, so i took some selfies, uploaded them to social club, but i have yet to see them in settings>snapmatic selfies&mugshots, all i get is that damn thumbnail that i can't even read. i'm happy to have found this issue here, so i know i'm not suffering alone, thank you all

**Comment by stroop17wafflr** [comment]
Shit, forgot this existed. I honestly haven't really experimented with anything, since the image I uploaded while the workaround still functioned, is still on my account. Hell, I haven't even been on GTA in a while.

> i'm happy to have found this issue here, so i know i'm not suffering alone, thank you all

Sorry about this, though. Glad we could help in some way. Hopefully this gets resolved soon.

**Comment by stroop17wafflr** [comment]
Worst thing about this, is that tutorials or anything on this stuff is scarce. So, the most help you're gonna get on this is here, and even we are at a loss.

**Comment by Syping** [comment]
> Worst thing about this, is that tutorials or anything on this stuff is scarce. So, the most help you're gonna get on this is here, and even we are at a loss.

We have to wait and see until next DLC, when it's not fixed by then, we are in the dark for real.
The crew emblem issue years ago got fixed after many months, and i heard recently the new cloud server causing issues with Crew emblems too, the more problems are in the system the better actually, because at some point the complaints getting more.
Just the thing which annoyed me most.. they removed the Social Club forums, so we can only discuss on platforms outside of their own and we get less attention because of that.
I hope that someone with a big audience will point out the current Social Club issues, because that would help getting attention for current problems.

**Comment by stroop17wafflr** [comment]
> We have to wait and see until next DLC, when it's not fixed by then, we are in the dark for real.

We've had this issue for about 2 DLCs now, and they have yet to fix it. I'm honestly kinda starting to lose hope with this. If they don't fix it next DLC, our last hope is contacting support, but I don't even know about that. The most we'll be getting the attention of, is their automated messengers.

> I hope that someone with a big audience will point out the current Social Club issues, because that would help getting attention for current problems.

Honestly sad that this is even necessary, but yeah.

**Comment by Syping** [comment]
> We've had this issue for about 2 DLCs now, and they have yet to fix it. I'm honestly kinda starting to lose hope with this. If they don't fix it next DLC, our last hope is contacting support, but I don't even know about that. The most we'll be getting the attention of, is their automated messengers.

I don't think they will fix these kind of issues in their mid-DLC updates.. even surprised they started doing mid-DLC updates in the first place.. in past they left bugs for half a year or even longer, but yea these mid-DLC updates would be actually perfect for fixes like this if they would care enough about these kind of issues.
I already feel horrified from Expanded and Enhanced.. i expect a total mess coming upon us.

**Comment by stroop17wafflr** [comment]
> I already feel horrified from Expanded and Enhanced.. i expect a total mess coming upon us.

That is a whole other issue in and of itself, a very disappointing one at that. 

This will probably impede the progress of any patches though, for obvious reasons.

**Comment by Syping** [comment]
> I don't know how much this matters honestly but I asked them about this like month ago and got this ![avatar](https://user-images.githubusercontent.com/92825684/137986701-108988b1-2c96-467f-a3bf-fc6d5353944f.jpg)

@ante2103 Thank you for showing this... it's good news that the support have a reference so at least we know they are internally aware of it.

**Comment by stroop17wafflr** [comment]
Sorry, got kicked out of GitHub, and had some trouble getting back in.

> I don't know how much this matters honestly but I asked them about this like month ago and got this

Thanks. Like @Syping said, at least they're aware of the issue now, if they weren't already.

**Comment by Syping** [comment]
I got few news about the current state of Snapmatic Avatars
- They removed all _small.jpg files, which seems they rework how Snapmatic Avatar works on the Server side (It could mean i would have to change the Avatar zone location aswell)
- You can't select either new or old pictures as Avatar now, all Avatars are blank
- The pictures i uploaded on a outdated build are deleted

The new "The Contract" DLC releases soon, i guess the new Web changes will go live after this update, when Avatar upload works again like before Tuners DLC, i will close the GitHub issue.
When Avatar uploads doesn't work at all, i will keep the GitHub issue open.
When they changed the Avatar zone, i will push a 1.10.2 update to address it.

**Comment by Syping** [comment]
The web changes are live, so Avatar upload could potentially work.
What i discovered so far... they use their Server based JPEG encoder to resize the pictures, which they introduced for their thumbnails at their last big Social Club update.
Don't had the time to start the game yet and upload a new picture... i probably will do that today evening at my time and report back.
Can anyone confirm it's fixed for them?

**EDIT:** It was possible to put a Avatar from the old server successfully... but haven't tested the new server so far.
**EDIT:** New server Avatar doesn't apply... but preview works.

**Comment by assassincheeta** [comment]
I just tried it... they haven't fixed it

**Comment by Syping** [comment]
> I just tried it... they haven't fixed it

@assassincheeta Thank you for reporting, tell me if anything changes in the next 30 minutes, applying a picture from the old Server took me very long. I will test the new Server later today.

**Comment by Syping** [comment]
**Update:** Avater previews mostly fixed, but applying Avatar from new server still doesn't work. My guess is that they still use _small.jpg files internally (even when we can't access them anymore), or they having issues getting pictures from the new server.
Issue will remain open, no update will be pushed.

**Comment by DOGyth** [comment]
> **Update:** Avater previews mostly fixed, but applying Avatar from new server still doesn't work. My guess is that they still use _small.jpg files internally (even when we can't access them anymore), or they having issues getting pictures from the new server. Issue will remain open, no update will be pushed.

HI BRO YOU HAVE A DISCORD, IM FAN OF YOU USE YOUR PROGRAM 4 YEAR A GO AND NOW IS BANED ;`<`

**Comment by Syping** [comment]
> > **Update:** Avater previews mostly fixed, but applying Avatar from new server still doesn't work. My guess is that they still use _small.jpg files internally (even when we can't access them anymore), or they having issues getting pictures from the new server. Issue will remain open, no update will be pushed.
> 
> HI BRO YOU HAVE A DISCORD, IM FAN OF YOU USE YOUR PROGRAM 4 YEAR A GO AND NOW IS BANED ;`<`

@DOGyth
I have no Discord guild, think the interest would be too small to make one too, unless enough people tell me my assumption would be entirely wrong
There is a issue currently going on with Snapmatic in general, so probably there is no ban at place at your account... and neither at the software itself.

**Comment by DOGyth** [comment]
> 

ah i know bro it external but i get ban random by rockstar ;`<

**Comment by neonxeon** [comment]
issue seems to be still present as of Dec 31, 2021.custom snapmatic avatars do not apply.

A question for creator, is there a way we can change when the picture was taken? does gta5view already have this feature?

**Comment by stroop17wafflr** [comment]
Doesn't surprise me that it still hasn't been fixed, R* was just too busy breaking/rigging the existing heists. 

I doubt "Snapmatic Avatars" is something on R*'s list of priorities, but this is something that could probably be easily fixed, yet it's just been left broken for about 6 months now.

Though, the avatar that I uploaded when the work-around was functioning is still up, and my friends can see it, weirdly enough.

**Comment by Syping** [comment]
> issue seems to be still present as of Dec 31, 2021.custom snapmatic avatars do not apply.
> 
> A question for creator, is there a way we can change when the picture was taken? does gta5view already have this feature?

@neonxeon Yes, the JSON Editor allows you to change the **creat** UNIX timestamp.

<img src="https://user-images.githubusercontent.com/9694335/147838165-1211a27f-55e3-4f48-9d3b-ff7cdcc9a500.png" alt="Snapmatic Viewer">
<img src="https://user-images.githubusercontent.com/9694335/147838178-6b16c302-f2e0-4638-b6cd-fb370fb23e96.png" height="515px" alt="JSON Editor">

UNIX timestamp: [unixtimestamp.com](https://www.unixtimestamp.com/), [unixtime.org](https://unixtime.org/)

**Comment by Syping** [comment]
> Doesn't surprise me that it still hasn't been fixed, R* was just too busy breaking/rigging the existing heists.
> 
> I doubt "Snapmatic Avatars" is something on R*'s list of priorities, but this is something that could probably be easily fixed, yet it's just been left broken for about 6 months now.
> 
> Though, the avatar that I uploaded when the work-around was functioning is still up, and my friends can see it, weirdly enough.

@GenericTuxedoGuy I have 2 theories about this... either they thought just the previews was broken... or the developer who went fixing it for them just fixed the previews and said hey look guys we fixed it.
I will give them another DLC to fix the next issue... think we need raise our voices again and make it clear they only fixed the previews and not the entire system.

**Comment by Syping** [comment]
If any Rockstar Web Developer reading this, the best way to fix the issue and ensure good quality and not breaking the old way of applying Snapmatic Avatar, do this.

1. Use the  **.jpg** file instead of the **_small.jpg** file.
2. Check if the picture is **960x536**... if not, error.
3. Set the left margin to **145px**, and the top margin to **66px**, then take **470px** from both sides, so the end result is **470x470**.
4. *Optional:* Resize the picture to **256x256**, **384x384** or just take the **470x470** one.

Example: https://github.com/SyDevTeam/gta5view/blob/1.10.x/res/avatararea.png

**Comment by Jiggy64** [comment]
So there is no way to get a custom profile picture, or is it possible? I remember that the first time I used gta5view, which was 6 days ago, I took a test run to see if it worked, but then I couldn't when trying to put the one I wanted

**Comment by stroop17wafflr** [comment]
> either they thought just the previews was broken...

Could be possible. We weren't really told the details of that support email that was sent, so it probably could've been a bit vague, and confused them.

> or the developer who went fixing it for them just fixed the previews and said hey look guys we fixed it.

Could also be that. Again, we didn't see the email, so this could just be a misunderstanding. Still frustrating, though.

**Comment by stroop17wafflr** [comment]
> So there is no way to get a custom profile picture, or is it possible? I remember that the first time I used gta5view, which was 6 days ago, I took a test run to see if it worked, but then I couldn't when trying to put the one I wanted

It is possible, just not at the moment. Going off of @Syping's theory, they basically just fixed half of it, because they didn't know the entire system was broken.

**Comment by Syping** [comment]
> So there is no way to get a custom profile picture, or is it possible? I remember that the first time I used gta5view, which was 6 days ago, I took a test run to see if it worked, but then I couldn't when trying to put the one I wanted

@Jiggy64 Currently sadly no, if you have any Snapmatic uploaded before the Tuners DLC you can use them... but any pictures uploaded after this will not work, doesn't matter if you made them in-game or with gta5view.

**Comment by MOLLY777b** [comment]
guyss it can work now！！！

**Comment by Syping** [comment]
> guyss it can work now！！！

@MOLLY777b YES YOU ARE RIGHT, IT WORKS NOWWW!!!
Sorry for caps too, i just had too after all the time :D

Thanks for whoever at Rockstar fixed it!!!

**Comment by stroop17wafflr** [comment]
Thank god. That took way too long to fix, but at least it has been.

**Comment by J4ckski** [comment]
Yup as of 19th January 2022  I can also confirm that snapmatic selfie uploads are now working on PC.  Not that we ever doubted R* of course.. ;p

**Comment by ante2103** [comment]
Did all avatars disappear for anyone else too?

**Comment by Jiggy64** [comment]
> Did all avatars disappear for anyone else too?

Bruh, I think do

**Comment by stroop17wafflr** [comment]
Same here. I hesitated even commenting on it, since it just started happening about a day ago, but shame on me for thinking R* would fix anything regarding Social Club, without being informed about it 20 times.

It looks like the system itself just completely crapped the bed, with even the default avatars missing. There's also another **(probably unrelated)** glitch, that will repeatedly tell anyone on your friends-list that you're online.

Nevermind, as of 8:30 EST, everything seems to be working again. The only thing that worked for me as far as uploading the avatar, was ticking "Qualify as Avatar at apply" in the Snapmatic's properties.

**Comment by Syping** [comment]
I just got worried when i started to read here lol... R* is just being funny atm.

**Comment by Pronater** [comment]
Apparently it's back to normal, at least for me it's working again.

**Comment by stroop17wafflr** [comment]
Yeah it is.

**Comment by Syping** [comment]
**Update:** R* have changed their system how new Custom Avatars are generated, when you have issues applying a Avatar, you need to reupload it.

**Old Avatar URL:** https&#58;&#47;&#47;a.rsg.sc/n/${username}/n/${size}
**New Avatar URL:** https&#58;&#47;&#47;www&period;prod-avatars.akamaized.net/custom-avatars/${size}/${photoid}.png

The new Avatar URL now matches with the URL from the Snapmatic photo id, R* doesn't update Avatar from the old Avatar URL anymore, which breaks how many FiveM RP Server implemented their User Avatar system by using people's Social Club avatar.
But i can't tell if R* did targeted to break FiveM RP Server avatars which (ab)used their service.

**Investigation Update 1:** When you change your Avatar, the old Avatar get's deleted from their Server, so you probably able to select a different Avatar for few minutes, and then select your Avatar you want again, i saw oddities with having different Avatar in Feed and Profile, and other browser having different Avatar in Profile too, these oddities probably related to how Akamai handles caching.
**Note:** It's not because of browser caching, their CDN returns the old Avatar URLs.
