### ISSUE TITLE
Imported pictures don't upload correctly

### ISSUE THREAD

**Issue by ghost** [SyDevTeam/gta5view#14]
When importing pictures from gta 5 view, setting them as an avatar and uploading it to Rockstar games gallery, turns the images into a corrupted file which doesn't show the picture at all.

This is a picture i uploaded.
![image](https://user-images.githubusercontent.com/83969413/140651500-5612e0a7-ad67-46de-92b2-769fb5a5f98f.png)

And this is the result in Rockstar's Avatar selection.
![image](https://user-images.githubusercontent.com/83969413/140651521-de717ff5-953d-46dd-b17b-77646bce7cc3.png)
Images from a while ago (6 months ish) still show correctly, but reuploading them does the same thing.

Is this a bug with gta view or is rockstar hammering down on this?

**Comment by Syping** [comment]
Duplication of https://github.com/SyDevTeam/gta5view/issues/13
