### ISSUE TITLE
Weird issue after uploading a Avatar Snapmatic from the game

### ISSUE THREAD

**Issue by howdoiusekeyboard** [SyDevTeam/gta5view#15]
Hello
I tried using this to upload my pic as avatar, I uploaded it to social club then set it as avatar from rockstar website and everything worked gr8
Later i tried doing everything from game but i faced something wierd 
![image](https://user-images.githubusercontent.com/90883505/152700262-11811e63-94d8-4c4e-80dd-59e1d235f7d7.png)

**Comment by Syping** [comment]
It's probably just Akamai related, try to upload another picture and apply it... even when it just only show text in the preview.
Had someone mention this issue few weeks ago on the [English Steam Guide](https://steamcommunity.com/sharedfiles/filedetails/?id=1121251146).
If it successfully applied within 30 minutes, it's only a glitch, when not... there might be another issue but we have to see if other people having that aswell.

**Comment by howdoiusekeyboard** [comment]
There are actually 3 pictures uploaded in here xD, it only shows 1 and that too buggy
We should prolly use the Rockstar website to set snapmatic pic as avatar after uploading picture from gallery to social club, that works great.
ig Rockstar left out fixing the game part and only fixed the website, as expected of Rockstar

**Comment by Syping** [comment]
Yea that can be probably the case, so long it does work in the website i don't see a real problem too, might update the Guides to tell people to use the Social Club website instead of the game overlay.

**Comment by DOGyth** [comment]
> Yea that can be probably the case, so long it does work in the website i don't see a real problem too, might update the Guides to tell people to use the Social Club website instead of the game overlay.

![image](https://user-images.githubusercontent.com/96627187/152830615-420b55c6-b5a9-4a2e-8942-4f21de1f1897.png)
i cant upload to rockstar
i get ban so i cant use feature online to upload?

**Comment by howdoiusekeyboard** [comment]
Yep I'm 99% sure thats related to your ban
Sorry for ya

**Comment by Syping** [comment]
> > Yea that can be probably the case, so long it does work in the website i don't see a real problem too, might update the Guides to tell people to use the Social Club website instead of the game overlay.
> 
> ![image](https://user-images.githubusercontent.com/96627187/152830615-420b55c6-b5a9-4a2e-8942-4f21de1f1897.png) i cant upload to rockstar i get ban so i cant use feature online to upload?

@DOGyth Yes probably... since you had to agree to the GTA Online ToS when uploading Snapmatic, when they terminate you from GTA Online you can't upload Snapmatic aswell.

**Comment by howdoiusekeyboard** [comment]
Btw i know this is a very foolish question, but I just wanted to ask anyways...
In the assests in your releases, whats the difference between gta5view-1.10.1_setup.exe and gta5view-1.10.1.exe? in terms of application/file methodology

**Comment by Syping** [comment]
The gta5view-1.10.1_setup.exe is a installable build, with dynamic libraries and dynamic resources and this kind of stuff, it register the .g5e file format for gta5view and is easier to mod.
And gta5view-1.10.1.exe is the Portable version, it's very similar to the version from gta5-mods etc. No installation required.

**Comment by clx127** [comment]
> Hello I tried using this to upload my pic as avatar, I uploaded it to social club then set it as avatar from rockstar website and everything worked gr8 Later i tried doing everything from game but i faced something wierd ![image](https://user-images.githubusercontent.com/90883505/152700262-11811e63-94d8-4c4e-80dd-59e1d235f7d7.png)

Same... I dont understand some buddys says that R* fixed issue and they can upload it, what a liar.... Goddamn it

**Comment by Syping** [comment]
> > Hello I tried using this to upload my pic as avatar, I uploaded it to social club then set it as avatar from rockstar website and everything worked gr8 Later i tried doing everything from game but i faced something wierd ![image](https://user-images.githubusercontent.com/90883505/152700262-11811e63-94d8-4c4e-80dd-59e1d235f7d7.png)
> 
> Same... I dont understand some buddys says that R* fixed issue and they can upload it, what a liar.... Goddamn it

@clx127 Use the [Social Club website](https://socialclub.rockstargames.com/)... we was talking about that before.
