### ISSUE TITLE
Still uploaded custom avatar doesnt shows up...

### ISSUE THREAD

**Issue by clx127** [SyDevTeam/gta5view#17]
I dont understand why on some posts somone says that Rockstar fixed issue but today i tryed to upload my custom avatar with JPG format and in game i pressed button to upload SC and in game settings my uploaded avatars shows with blank texts.... So whats wrong now? Or i need to change it to PNG format?

**Comment by Syping** [comment]
Duplicate of https://github.com/SyDevTeam/gta5view/issues/15
