### ISSUE TITLE
A way to edit save game created date?

### ISSUE THREAD

**Issue by neonxeon** [SyDevTeam/gta5view#18]
just like we can edit when a snapmatic picture was taken using the unix create integer, would it be possible to just add this feature to edit savegame created unix timestamp? 

I also have a another question for author, is there a way we can change "Track" played metadata of the snapmatic file?

**Comment by Syping** [comment]
> just like we can edit when a snapmatic picture was taken using the unix create integer, would it be possible to just add this feature to edit savegame created unix timestamp?

@neonxeon Savegame can't be edited in gta5view, which i would love to add but it requires lots reverse engineering of my part, there other Savegame editors but they don't contribute back to the community at all.

> I also have a another question for author, is there a way we can change "Track" played metadata of the snapmatic file?

@neonxeon Track played i think is "scr" in JSON editor, but i have no list of tracks, i would have to make a Snapmatic with each Track to collect all IDs.
