### ISSUE TITLE
Pictures corrupt when overwritten

### ISSUE THREAD

**Issue by nono17k** [SyDevTeam/gta5view#19]
whatever i do with this program it seams that every picture i try to made usabe as a pfp end up being seen as corpted by the game any idea on how to fix that ?
![image](https://user-images.githubusercontent.com/28670447/224178444-68f37e39-2a6f-4a60-950e-bbba3d0cc93c.png)

**Comment by Syping** [comment]
I have few questions so we can narrow down the issue:

1. Have you restarted your game after you used gta5view?
2. What settings you choose when you imported your picture? A screenshot from gta5view could help

Example...

![Import Interface](https://user-images.githubusercontent.com/9694335/224196879-47b69dda-b4f6-41ef-9f2b-90832c2675d4.png)

**Comment by nono17k** [comment]
yea i did both before sending this and there were not the problem

**Comment by Syping** [comment]
> yea i did both before sending this and there were not the problem

can you send me screenshots from the gta5view Import proccess? because pictures should not corrupt

**Comment by Syping** [comment]
Will discuss this issue now here: https://github.com/SyDevTeam/gta5view/issues/20
