### ISSUE TITLE
Modified Snapmatic can no longer be uploaded to Social Club

### ISSUE THREAD

**Issue by RaptorX72** [SyDevTeam/gta5view#20]
It appears ever since the new update, modified snapmatic files cannot be uploaded to Social Club.
I have done the following tests:

- Imported an image (Profiles > Import files > Default settings)
Went to game, recorded a clip, made two screenshots in editor, then:
- Left one unmodified
- Changed second snapmatic via Manage > Overwrite image > Options > Import new picture > Default settings

After restarting GTA 5, the only image that could be uploaded to Social Club was the unmodified clip screenshot.

**Comment by Syping** [comment]
Thanks for the report, i recently confirmed the issue within the Steam guide discussion, i will look into it further when i have the time.

**Comment by Ripperinooo** [comment]
I have found a workaround:
Basically all you do is take a selfie in game.
Then you try to upload that picture and wait on the confirm screen.
Then in GTA5View overwrite the current image with the image you want.
Then go back to GTA and just press enter to confirm and upload the image.

**Comment by Syping** [comment]
I did an update, please test the recent 1.10.2 release and see if it's fixed for you now.

**Comment by RaptorX72** [comment]
I tried the same cases as before, every option shows the upload button, images appear on Social Club as well. Fixed.

**Comment by Syping** [comment]
> I tried the same cases as before, every option shows the upload button, images appear on Social Club as well. Fixed.

Thanks, i will close the issue then.
