### ISSUE TITLE
Out of date AUR packages

### ISSUE THREAD

**Issue by Tarballwalf** [SyDevTeam/gta5view#21]
I figured I'd leave this here, since you're more likely to see it

both of your packages found on the arch user repository are now out of date
https://aur.archlinux.org/packages/gta5view-bin
https://aur.archlinux.org/packages/gta5view

**Comment by Syping** [comment]
Thanks for reminding me, i will do it as soon i have the time, i have being switching to Fedora as my main distribution a few time ago so i didn't came to handle the AUR stuff yet.

**Comment by Syping** [comment]
I dealt with the gta5view package for now, gta5view-bin will come next, have to deal with the Open Build Service package aswell.

**Comment by Syping** [comment]
Both AUR packages now updated.
