### ISSUE TITLE
Allow custom game save path

### ISSUE THREAD

**Issue by Bad3r** [SyDevTeam/gta5view#22]
Hello,
I built gta5view locally, and when I attempted to open the game save folder, nothing happened. Is there a way to debug this issue?

https://github.com/SyDevTeam/gta5view/assets/25513724/6eceab20-2935-43ff-826e-4dc18cc1c178

**Comment by Syping** [comment]
In your GTA V folder the "Profiles" folder is missing, you need have a structure like this: "GTA V/Profiles/$YOUR_ID"
This should fix your issue.

**Comment by Bad3r** [comment]
> In your GTA V folder the "Profiles" folder is missing, you need have a structure like this: "~/Documents/GTA V/Profiles/$YOUR_ID" This should fix your issue.

I am using Linux with Wine so the path is different. I'll setup a syslink. It would be nice if you allowed the user to select the directory. 

Thank you for the quick response. It's good to close if you don't want to convert it to a request to add a custom path.

**Comment by Syping** [comment]
In the options dialog you can set a directory you want to use
And there is the GTAV_FOLDER environment variable to set the GTA V folder, which needs to follow the Profile structure

For 1.11.0 i planned to detect automatically the Proton savegame folder on Linux

Important is that the Profile structure is in tact, i edited the last post to better reflect it

**Comment by Bad3r** [comment]
That makes sense, thank you. Once I opened the profile, the only option I was prompted with was 'export profile.' I am unable to do anything else with the game save.

**Comment by Syping** [comment]
> That makes sense, thank you. Once I opened the profile, the only option I was prompted with was 'export profile.' I am unable to do anything else with the game save.

Yea that's right, i don't have any savegame editing features built-in, only picture editing stuff (Snapmatic).

**Comment by Syping** [comment]
I will close the issue for now, but you can keep asking new questions etc.
