### ISSUE TITLE
VirusTotal says this is a virus

### ISSUE THREAD

**Issue by Caprincot** [SyDevTeam/gta5view#23]
https://www.virustotal.com/gui/file/fc0a3cd69e60260f9c87c68354c8196fbae556dea6aa6a95f371d3eb99e88a17

**Comment by Syping** [comment]
It's a false positive with one of the engines used by VirusTotal, lot of AI anti virus are known to trigger a lot of false positive.
I saw with a quick research Bkav Pro is very known to cause false positive too, so it's really a non issue with gta5view or any other project which get flagged by Bkav Pro.
