### ISSUE TITLE
Custom avatars not applying to account but snapmatics changed from editor to selfie do

### ISSUE THREAD

**Issue by lnfraction** [SyDevTeam/gta5view#24]
As title says, whenever I create a custom avatar and upload it to SC, this image does not apply to my account when applying via avatar menu. It results in a grey R* icon appearing, and no change being reflected. Images taken in-game (even in normal Snapmatic mode or editor) work for avatars.

**Comment by Syping** [comment]
You should do some following tests:
- Test if "Overwrite Image..." does work
- Upgrade gta5view to 1.10.2 if not done yet

If none of it works, send me one working Snapmatic (which you can put as Avatar), and one which doesn't work, so i can investigate the issue.

**Comment by lnfraction** [comment]
Here, I can add the first one but when I try to use the second one (which is perfectly centered unlike the first one) it just shows the grey icon and doesn't apply.
![images](https://github.com/SyDevTeam/gta5view/assets/171673808/07648b9a-698f-49da-8969-a196d2b0efb7)
![images (2)](https://github.com/SyDevTeam/gta5view/assets/171673808/e71e6d01-f47e-40b2-996e-332d77763f33)

**Comment by Syping** [comment]
Can you use the Export feature and upload the exported Snapmatic?
The Snapmatic format have some metadata inside and i think it could be the reason
Any exported format is fine

**Comment by Syping** [comment]
A issue reference about "perfectly centered unlike the first one" https://github.com/SyDevTeam/gta5view/issues/9

**Context:** In the Avatar selection the Avatar are differently centered than after applying them
