### ISSUE TITLE
How to change Snapmatic creation date?

### ISSUE THREAD

**Issue by Grefetger** [SyDevTeam/gta5view#25]
Hi. Thank you so much for this wonderful program. 
Could you please tell me if it is possible to change the Snapmatic photo creation date (the date when the photo was taken) to any other date so that it also will be displayed correctly on the RGSC website as well? If possible, how? Thank you!
![изображение_2024-07-16_201358082](https://github.com/user-attachments/assets/761a91e2-e2e8-485a-83bf-1b7b03ff386f)

**Comment by Syping** [comment]
Yes, it's possible! You have to replace the "creat" JSON value with a new [UNIX timestamp](https://www.unixtimestamp.com/) in the JSON editor.
After you changed the UNIX timestamp you need to reupload the picture, by deleting it on the website.

![JSON Editor creat variable](https://github.com/user-attachments/assets/7a94ee35-b4fc-45a1-9e1c-96b6bd6fdefb)

**Comment by Grefetger** [comment]
> Yes, it's possible! You have to replace the "creat" JSON value with a new [UNIX timestamp](https://www.unixtimestamp.com/) in the JSON editor. After you changed the UNIX timestamp you need to reupload the picture, by deleting it on the website.
> 
> ![JSON Editor creat variable](https://private-user-images.githubusercontent.com/9694335/349300658-7a94ee35-b4fc-45a1-9e1c-96b6bd6fdefb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzM0NjIsIm5iZiI6MTcyMTQ3MzE2MiwicGF0aCI6Ii85Njk0MzM1LzM0OTMwMDY1OC03YTk0ZWUzNS1iNGZjLTQ1YTEtOWUxYy05NmI2YmQ2ZmRlZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMTA1OTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjA1ZmFkMDIxMzZiYTQzMmYxYTJiZDEwYjY3ZjZkOWNhZTRiZjZmOTZhZGJlMTMxYmNmZjJjMDRkMmRkMjQ4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GxX9pY8Z7SwKMqnXkzqSTrGhZMHDfkINSDpGBHcDILo)

Thank you!
