### ISSUE TITLE
bad position?

### ISSUE THREAD

**Issue by elfl0rd** [SyDevTeam/gta5view#9]
![default](https://user-images.githubusercontent.com/4980243/43690724-ba8d0220-9917-11e8-8491-b963042295b0.png)

**Comment by VADemon** [comment]
This is only a visual glitch inside SocialClub (website), because Rockstar themselves broke the layout.
It will look correct in-game.

**Comment by elfl0rd** [comment]
its visible on social club :(

**Comment by elfl0rd** [comment]
can you allow little avatar position move?

**Comment by Syping** [comment]
After applying the avatar it will moved to the correct position, it's not possible to change the position which Social Club select the Avatar from so it's hardcoded.

**Example (Social Club issue)**
![Example Picture](https://i.imgur.com/Um4ll3u.png)

**Comment by Syping** [comment]
**Workaround:** https://github.com/Syping/socialclub-avatar-zone-fix
